services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    restart: always
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:123@postgres:5432/task_manager
    ports:
      - "3000:3000"
    command: sh -c "npm run migration:run:prod && npm run start:prod"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
